spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch1?createDatabaseIfNotExist=true
    username: nimauser
    password: 1234

  uni:
    url: jdbc:mysql://localhost:3306/spring_batch2?createDatabaseIfNotExist=true
    username: nimauser
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always